### ISSUE TITLE
[polyglot-groovy] Reinstate unit test execution

### ISSUE THREAD

**Issue by fbricon** [takari/polyglot-maven#48] opened 2015-09-14 17:17 UTC
Unit tests are not executed during Maven builds of polyglot-groovy.

They can run from Eclipse though (after installing the m2e-groovy connector). However, 3 tests (GroovyModelWriterTest#testWriting, GroovyModelReaderTest#testExecute,  GroovyModelReaderTest#testReading) fail with CNFE like 
```
java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/typehandling/ShortTypeHandling
	at org.sonatype.maven.polyglot.groovy.GroovyModelTestSupport.load(GroovyModelTestSupport.groovy:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:266)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:51)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:44)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:143)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:151)
	at org.sonatype.maven.polyglot.groovy.GroovyModelWriterTest.testWriting(GroovyModelWriterTest.groovy:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.typehandling.ShortTypeHandling
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 30 more
```

Adding the following snippet to `polyglot-groovy/pom.xml` can reinstate compilation and execution of unit tests, yielding the same errors:

```
	<properties>
		<groovy.compiler.version>2.9.2-01</groovy.compiler.version>
	</properties>
	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.groovy</groupId>
				<artifactId>groovy-eclipse-compiler</artifactId>
				<version>${groovy.compiler.version}</version>
				<extensions>true</extensions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version><!--$NO-MVN-MAN-VER$ -->
				<configuration>
					<compilerId>groovy-eclipse-compiler</compilerId>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.codehaus.groovy</groupId>
						<artifactId>groovy-eclipse-compiler</artifactId>
						<version>${groovy.compiler.version}</version>
					</dependency>
					<dependency>
						<groupId>org.codehaus.groovy</groupId>
						<artifactId>groovy-eclipse-batch</artifactId>
						<version>2.4.3-01</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>
```

The code compile against groovy 1.7.3. That missing org.codehaus.groovy.runtime.typehandling.ShortTypeHandling is supposed to happen when mixing bits from old groovy versions and groovy 2.3.5+ (See http://glaforge.appspot.com/article/groovy-2-3-5-out-with-upward-compatibility). Adding the compatibility jar to the classpath (or plugin classpath) didn't fix anything.  

But ideally, the groovy dependency should be bumped to the latest release (2.4.4), but then you get into more issues.

```
  testBuildParseGoals1(org.sonatype.maven.polyglot.groovy.builder.ModelBuilderTest): No such property: _SCRIPT_CLASS_NAME_ for class: org.apache.maven.model.Model
  testBuildParseGoals2(org.sonatype.maven.polyglot.groovy.builder.ModelBuilderTest): No such property: _SCRIPT_CLASS_NAME_ for class: org.apache.maven.model.Model
  testBuildWithConfiguration(org.sonatype.maven.polyglot.groovy.builder.ModelBuilderTest): No such property: _SCRIPT_CLASS_NAME_ for class: org.apache.maven.model.Model
  testExecute(org.sonatype.maven.polyglot.groovy.GroovyModelReaderTest): Cannot set property '_SCRIPT_CLASS_NAME_' on null object
  testReading(org.sonatype.maven.polyglot.groovy.GroovyModelReaderTest): Cannot set property '_SCRIPT_CLASS_NAME_' on null object
```

I don't know enough about groovy to be able to fix the issue myself, so if anyone could help, or give me some directions, that'd be much appreciated. @jdillon or @Randgalt, any ideas?

**Comment by Randgalt** [comment] 2015-09-14 17:24
I know next to nothing about Groovy. I only worked on the IntelliJ Groovy/Maven thing because I needed to convince some folks to use Maven.

**Comment by jdillon** [comment] 2015-09-14 18:28
groovy 1.7.3 pretty ancient and likely not compatible with the latest groovy-eclipse-compiler, probably should update to use a more modern version of groovy.

—jason




On September 14, 2015 at 10:17:10 AM, Fred Bricon (notifications@github.com) wrote:

Unit tests are not executed during Maven builds of polyglot-groovy.

They can run from Eclipse though (after installing the m2e-groovy connector). However, 3 tests (GroovyModelWriterTest#testWriting, GroovyModelReaderTest#testExecute, GroovyModelReaderTest#testReading) fail with CNFE like

java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/typehandling/ShortTypeHandling
    at org.sonatype.maven.polyglot.groovy.GroovyModelTestSupport.load(GroovyModelTestSupport.groovy:33)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:266)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:51)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:44)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:143)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:151)
    at org.sonatype.maven.polyglot.groovy.GroovyModelWriterTest.testWriting(GroovyModelWriterTest.groovy:41)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at junit.framework.TestCase.runTest(TestCase.java:176)
    at junit.framework.TestCase.runBare(TestCase.java:141)
    at junit.framework.TestResult$1.protect(TestResult.java:122)
    at junit.framework.TestResult.runProtected(TestResult.java:142)
    at junit.framework.TestResult.run(TestResult.java:125)
    at junit.framework.TestCase.run(TestCase.java:129)
    at junit.framework.TestSuite.runTest(TestSuite.java:255)
    at junit.framework.TestSuite.run(TestSuite.java:250)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.typehandling.ShortTypeHandling
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 30 more

Adding the following snippet to polyglot-groovy/pom.xml can reinstate compilation and execution of unit tests, yielding the same errors:

    <properties>
        <groovy.compiler.version>2.9.2-01</groovy.compiler.version>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.groovy</groupId>
                <artifactId>groovy-eclipse-compiler</artifactId>
                <version>${groovy.compiler.version}</version>
                <extensions>true</extensions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <compilerId>groovy-eclipse-compiler</compilerId>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-compiler</artifactId>
                        <version>${groovy.compiler.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-batch</artifactId>
                        <version>2.4.3-01</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

The code compile against groovy 1.7.3. That missing org.codehaus.groovy.runtime.typehandling.ShortTypeHandling is supposed to happen when mixing bits from old groovy versions and groovy 2.3.5+ (See http://glaforge.appspot.com/article/groovy-2-3-5-out-with-upward-compatibility). Adding the compatibility jar to the classpath (or plugin classpath) didn't fix anything.

But ideally, the groovy dependency should be bumped to the latest release (2.4.4), but then you get into more issues.

  testBuildParseGoals1(org.sonatype.maven.polyglot.groovy.builder.ModelBuilderTest): No such property: _SCRIPT_CLASS_NAME_ for class: org.apache.maven.model.Model
  testBuildParseGoals2(org.sonatype.maven.polyglot.groovy.builder.ModelBuilderTest): No such property: _SCRIPT_CLASS_NAME_ for class: org.apache.maven.model.Model
  testBuildWithConfiguration(org.sonatype.maven.polyglot.groovy.builder.ModelBuilderTest): No such property: _SCRIPT_CLASS_NAME_ for class: org.apache.maven.model.Model
  testExecute(org.sonatype.maven.polyglot.groovy.GroovyModelReaderTest): Cannot set property '_SCRIPT_CLASS_NAME_' on null object
  testReading(org.sonatype.maven.polyglot.groovy.GroovyModelReaderTest): Cannot set property '_SCRIPT_CLASS_NAME_' on null object

I don't know enough about groovy to be able to fix the issue myself, so if anyone could help, or give me some directions, that'd be much appreciated. @jdillon or @Randgalt, any ideas?

**Comment by fbricon** [comment] 2015-09-14 18:48
indeed, that would be the plan, but as I said, I'm stuck with the new `No such property: _SCRIPT_CLASS_NAME_ for class` issues.

**Comment by jdillon** [comment] 2015-09-14 20:22
So something related to invokeMethod has defs changed in more modern groovy versions.  I think I may have a solution, but need to test and see if it has any more wrinkles.

—jason




On September 14, 2015 at 11:48:20 AM, Fred Bricon (notifications@github.com) wrote:

indeed, that would be the plan, but as I said, I'm stuck with the new No such property: _SCRIPT_CLASS_NAME_ for class issues.

**Comment by jdillon** [comment] 2015-09-14 21:00
Here you guys go:

https://github.com/takari/polyglot-maven/pull/51

I’ve not done any extensive testing, but it at least compiles and runs tests now with the latest Groovy 2.4.4.

—jason




On September 14, 2015 at 1:21:58 PM, Jason Dillon (jason@planet57.com) wrote:

So something related to invokeMethod has defs changed in more modern groovy versions.  I think I may have a solution, but need to test and see if it has any more wrinkles.

—jason




On September 14, 2015 at 11:48:20 AM, Fred Bricon (notifications@github.com) wrote:

indeed, that would be the plan, but as I said, I'm stuck with the new No such property: _SCRIPT_CLASS_NAME_ for class issues.

**Comment by fbricon** [comment] 2015-09-14 21:24
That's pretty awesome @jdillon, thanks for looking into it. I just checked it builds and runs tests locally. Also tested the groovy extension on a separate sample project. Success \o/

**Comment by jvanzyl** [comment] 2015-09-14 22:43
Woo hoo!

**Comment by jdillon** [comment] 2015-09-14 22:49
@jvanzyl probably can close this issue unless there are more related problems.

**Closed** 2015-09-14 22:49 UTC

**Comment by mosabua** [comment] 2015-09-15 04:13
Nice work! Another thing to show at J1 ;-)
