### ISSUE TITLE
[feature request] Groovy - option to do translation using GAV string

### ISSUE THREAD

**Issue by paulvi** [takari/polyglot-maven#90] opened 2016-04-21 11:40 UTC
Groovy flavour supports shorter notation of dependencies as GAV string

```groovy
dependencies{
    dependency ("org.slf4j:slf4j-api:1.7.16"){}
}
```

however default translation is into longer  5 lines instead of 1.

While some may prefer #89 to have default that is closer to XML, could there be an option to translate into the shortest notation possible.

**Comment by jdillon** [comment] 2016-04-21 17:23
@paulvi as I mentioned in #89 the translation works on the canonical xml format, so its non-trivial to have it translate to a different format based on preferences of a user.

I'm not sure its worth the effort to change this, adding complexity to the translation, and potentially introducing problems where translation outputs invalid pom.groovy.

**Comment by jdillon** [comment] 2016-04-21 17:29
This is a duplicate of #49

**Closed by jdillon** 2016-04-21 17:29 UTC
Labels: enhancement, groovy

**Comment by paulvi** [comment] 2016-04-22 16:14
@jdillon Jason, I disagree.

First, it is not duplicate, as this issue is about do it option e.g. `pom.groovy` or `pom.gy` with more compact code. (See also #65 where is goes about '.xml' and '.xml41' )

> I'm not sure its worth the effort to change this, adding complexity to the translation, and potentially introducing problems where translation outputs invalid pom.groovy.

Second, while the code was mostly written by you, you are not supposed to put this in your TODO list. In fact, I need a guidance to implement myself. And the issue may stay open to see other users are interested (GitHub now have voting via selecting :+1: )

In #89 we agreed that he canonical xml format would be default.
