### ISSUE TITLE
Plugin dependencies result in a ClassCastException (polyglot-yaml)

### ISSUE THREAD

**Issue by marchev** [takari/polyglot-maven#36] opened 2015-05-18 20:53 UTC
Hi,

First of all I would like to thank for your effort and this project. I have been playing with the extension for some time and I really like it so far!

I have just found a bug with the handling of the plugin dependencies. I am using the latest version of `polyglot-yaml` at the time of writing - `0.1.9`. Whenever I add some plugin dependencies to my `pom.yml` I get the following exception:

```
[ERROR] Internal error: java.lang.ClassCastException: org.codehaus.plexus.util.xml.Xpp3Dom cannot be cast to org.apache.maven.model.Dependency -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.ClassCastException: org.codehaus.plexus.util.xml.Xpp3Dom cannot be cast to org.apache.maven.model.Dependency
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassCastException: org.codehaus.plexus.util.xml.Xpp3Dom cannot be cast to org.apache.maven.model.Dependency
    at org.apache.maven.model.io.xpp3.MavenXpp3Writer.writePlugin(MavenXpp3Writer.java:1402)
    at org.apache.maven.model.io.xpp3.MavenXpp3Writer.writeBuild(MavenXpp3Writer.java:329)
    at org.apache.maven.model.io.xpp3.MavenXpp3Writer.writeModel(MavenXpp3Writer.java:1115)
    at org.apache.maven.model.io.xpp3.MavenXpp3Writer.write(MavenXpp3Writer.java:100)
    at org.sonatype.maven.polyglot.TeslaModelProcessor.read(TeslaModelProcessor.java:109)
    at org.sonatype.maven.polyglot.TeslaModelProcessor.read(TeslaModelProcessor.java:86)
    at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:529)
    at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:269)
    at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:469)
    at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:438)
    at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:401)
    at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
    at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
    at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
    at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    ... 11 more
```

Please find below my `pom.yml` file and the original corresponding `pom.xml` files.

**pom.yml**

```
modelVersion: 4.0.0
groupId: org.marchev
artifactId: groovy-playground
name: groovy-playground project
version: 1.0-SNAPSHOT

dependencies:
  - { groupId: junit, artifactId: junit, version: 4.12, scope: test }
  - { groupId: org.codehaus.groovy, artifactId: groovy-all, version: 2.4.3 }

build:
  plugins:
    - groupId: org.codehaus.groovy
      artifactId: groovy-eclipse-compiler
      version: 2.9.2-01
      extensions: true
    - artifactId: maven-compiler-plugin
      version: 3.3
      configuration:
        compilerId: groovy-eclipse-compiler
        source: 1.8
        target: 1.8
      dependencies:
        - groupId: org.codehaus.groovy
          artifactId: groovy-eclipse-compiler
          version: 2.9.2-01
        - groupId: org.codehaus.groovy
          artifactId: groovy-eclipse-batch
          version: 2.4.3-01
```

**pom.xml**

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.marchev</groupId>
    <artifactId>groovy-playground</artifactId>
    <name>groovy-playground project</name>
    <version>1.0-SNAPSHOT</version>


    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.3</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.groovy</groupId>
                <artifactId>groovy-eclipse-compiler</artifactId>
                <version>2.9.2-01</version>
                <extensions>true</extensions>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <compilerId>groovy-eclipse-compiler</compilerId>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-compiler</artifactId>
                        <version>2.9.2-01</version>
                    </dependency>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-batch</artifactId>
                        <version>2.4.3-01</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

</project>
```

**Comment by jvanzyl** [comment] 2015-05-18 21:10
I'll update the examples to reproduce and get back to you.

**Comment by asomov** [comment] 2015-09-26 12:38
I cannot reproduce it. See the test:
https://github.com/asomov/polyglot-maven/blob/master/polyglot-yaml/src/test/java/org/sonatype/maven/polyglot/yaml/Issue36Test.java

I have also added the short version (which also just works):
https://github.com/asomov/polyglot-maven/blob/master/polyglot-yaml/src/test/resources/issue36-short.yaml

**Comment by mosabua** [comment] 2018-03-02 03:51
This seems to work just fine now. Closing.

**Closed by mosabua** 2018-03-02 03:51 UTC
