### ISSUE TITLE
Release Plugin

### ISSUE THREAD

**Issue by t1** [takari/polyglot-maven#120] opened 2017-03-10 06:55 UTC
I'm wondering how the POM manipulations that the release plugin does could work on a polyglot maven POM. Wouldn't this require a major update to the release plugin, so it provides hooks the polyglot extensions can use to do the actual changes? Or is it feasible to reverse-engineer the changes the plugin did and re-apply those to the polyglot model? If the version is somehow derived or stored in a custom manner, these hooks would have to be passed to the model code, so e.g. a groovy script can update that source.

I'm writing this, because I have the exactly this problem with my [pomx](https://github.com/t1/pomx) project and I'm wondering if you have already have some concept for this. I didn't find any.

**Comment by lefou** [comment] 2017-10-17 20:15
(this answer reflects my personal opinion)

I think the way the release plugin works (by modifying the local pom's) is broken by design and should be avoided. Editing the pom's via this plugin is IMHO simply some kind of timesaver and workaround around a design decision in Maven. And it is incompatible to polyglot. As the polyglot poms are in most cases more elaborated that `pom.xml`s ever could be, versions are probably held in variables and can not easily changed by a plugin without deep code understanding. Re-generating of these poms (from XML or any other Maven model) would most probably loose information.

In the polyglot-scala dialect (for example) it is possible and even encouraged to use a shared include file to store the project version. When you need to update the version, e.g. as part of a release, you simply edit that single source as you would do it with almost any other build system.

Of course you can establish some conventions for such an included resource or your choice of dialect and even write a plugin which will update it programmatically, but this will be behind the scope of the maven-release-plugin.

**Comment by t1** [comment] 2017-10-18 04:01
@lefou: So the release plugin would need to call some form of hook API that the polyglots can use, right? And there is no such thing, yet? Should we try to define one and maybe build a prototype?

**Comment by lefou** [comment] 2017-10-18 06:10
@t1 No, that's not what I meant to say. To make it clear, I don't want any plugin to manipulate my pom's. And as long as the release plugin wants to actively manipulate my poms and my version control system, I can only discourage from it's use.

**Comment by t1** [comment] 2017-10-18 09:59
@lefou: I was thinking of some callback API that the release plugin calls and the polyglot extensions implement, so the steps required when releasing can be performed by the polyglot extensions, and not the release plugin manipulating the pom directly.

**Comment by lefou** [comment] 2017-10-18 10:12
@t1 I have no clue what you have in mind, what the callback should do. Take the polyglot-scala dialect as an example and one of the showcase projects from the [README.md](https://github.com/takari/polyglot-maven/blob/15618f73da4998395a710d68adc894f37cb5054f/README.md#scala). The extension has no way to figure out were the version is specified, as it is most probably a variable defined elsewhere.  If fact, non of these four projects has the version as literal where you would expect it. As I said, I think the way the release plugin works is fundamental wrong. The motivation for it, cluttered versions around many pom files, can be avoided at the root, at least for the scala dialect. I don't know the other dialects that well to include/exclude them from that bold statement. But at least, I can not imaging what such an API should do in the Scala case.

**Comment by t1** [comment] 2017-10-18 11:11
@lefou: When running the `maven-release-plugin`, at some point it wants to change the version (and the scm url and more). It now does so by directly reading the `pom.xml`, updating the version, writing it back, and committing the change. This does not work for the polyglot extensions, as there may be no `pom.xml` or even if there is, it's not the master: A different file would have to be manipulated, e.g. the `pom.scala`.

The release plugin would be the wrong place to know about all polyglot extensions, so it would be better to build an API that the release plugin calls, and the polyglot extension implements. In the case of the [domino scala.pom](https://github.com/domino-osgi/domino/blob/master/pom.scala), this would mean that the `polyglot-scala` extension would have to find out that the `ScalaModel` property `gav` includes the `val dominoVersion` and update that version. I'm aware that this means parsing the `pom.scala`, analysing the references, changing the AST, and writing it back, and that there are cases where this is not possible due to conditional or otherwise complex version logic. But for most standard use-cases, this should work without any problem. And for yaml or other static file formats, it would be very easy.

I think the release plugin has it's place and most of its features actually work quite nicely even with polyglot extensions; only these pom manipulations fail.

**Comment by mkristian** [comment] 2017-10-18 12:24
my two cents from ruby projects using the maven-polyglot - the version can come from anywhere: a ruby constant somewhere in the pom.rb or even from the underlying gemspec file used as a base for the pom.rb or just have each pom read a file `VERSION` from the root directory. I feel the assumption of the release-plugin is to strict and maybe not suitable for real world projects using different DSL then XML.

**Comment by t1** [comment] 2017-10-18 12:31
Too much magic (non-standardized, non-declarative) for something as basic as the version doesn't look very maven-esque to me ;-)

**Comment by lefou** [comment] 2017-10-18 13:43
But that's a fact. A buildsystem has to serve the developer, not otherwise. Maven has a lot more restrictions than tools in other language eco systems. That is not bad per se, but also not ideal. I left Maven some years ago, or at least tried various other tools, even wrote some by myself. Polyglot brought me (partially) back, because it makes those restrictions manageable. I see polyglot more as a pom generator than as a other pom representation.

**Comment by t1** [comment] 2017-10-19 06:55
I don't mind this discussion getting philosophical ;-)

I think there are two extremes: dynamic vs. static... and both have advantages as well as disadvantages. Maven is designed to be completely in the static domain, and this is what many like about it, including me: The build phases are fixed, so you can rely on the basic sequence of steps to be performed. Some steps may do more or less, but the intention of the steps is predefined.

Ant and gradle OTOH are very dynamic, and that's what many like about them: They both allow you to do any steps in any order. This is great for some use-cases, and it's a matter of taste, if you prefer one or the other.

What I don't like about maven is the verbosity (but [the problem is not xml](https://github.com/t1/pomx)), and this is where polyglot maven can really help. The release plugin only works because of the strict scheme of maven. In gradle you would write your own release task, which is actually not so much work, but in maven this can be written generically _because of_ the strictness of the schema.

Trying to turn maven into gradle feels strange to me; why not use gradle in the first place? Gradle is cool!

**Comment by mosabua** [comment] 2018-03-02 04:10
I am inclined to close the issue due to the workings of the release plugin and no desire on my part to fix the release plugin to work with polyglot. Objections? I could add a note to the readme about known limitations ...

**Comment by t1** [comment] 2018-03-02 07:01
After rethinking the issue, I think when the pom is built with executing code, it would be appropriate for the release plugin to call back into the build script, i.e. it would call a method in your script named `setVersion`. If that method doesn't exist, the release plugin would fail. If it exists, it can do whatever is required to set the version, maybe in an external file, maybe by manipulating it's own source. 

A second method `setScm` with the uri and the tag or branch would be optional.

If nobody but me assumes this was something worth thinking about, we can close the issue ;-)

**Comment by lefou** [comment] 2018-03-02 08:59
+1 for closing this issue
+1 for making a note on the project README about limitations and a list of incompatible plugins.

**Comment by mosabua** [comment] 2018-03-03 18:00
We do not control how the release plugin works. If you or whoever feels inclined to work it can get that or some other solution that just uses the mode implemented, we can reopen the issue @t1 .

**Comment by mosabua** [comment] 2018-03-03 18:02
Added related note to readme.

https://github.com/takari/polyglot-maven/commit/1d9025de610d220d77a11419791b84864eef95a3

Closing issue

**Closed by mosabua** 2018-03-03 18:02 UTC
